# Generated by Django 4.0.6 on 2023-02-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecl',
            name='journal',
        ),
    ]
