# Generated by Django 4.0.6 on 2023-03-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementsFr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('montant', models.FloatField()),
                ('Mode', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('E', 'Envoyer'), ('R', 'Recevoire')], max_length=1)),
                ('Devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.devises')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.fournisseur')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.journal')),
            ],
        ),
    ]
