# Generated by Django 4.0.6 on 2023-02-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0002_remove_facturecl_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecl',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finanance.journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finanance.journal'),
            preserve_default=False,
        ),
    ]
