# Generated by Django 4.0.6 on 2023-02-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0003_facturecl_journal_notes_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiements',
            name='journal',
        ),
    ]
