# Generated by Django 4.0.6 on 2023-02-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0005_paiements_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecl',
            name='Taxe',
        ),
        migrations.RemoveField(
            model_name='facturefr',
            name='Taxe',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Taxe',
        ),
    ]
