# Generated by Django 4.0.6 on 2023-01-31 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0007_facturecl_journal_facturefr_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Mode', models.CharField(max_length=100)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.client')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.journalpaiement')),
            ],
        ),
    ]
