# Generated by Django 4.0.6 on 2023-01-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0008_journalpaiement_paiements'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='Type',
            field=models.CharField(choices=[('E', 'Envoyer'), ('R', 'Recevoire')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
