# Generated by Django 4.0.6 on 2023-02-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0011_rename_htaxe_facturecl_taxe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=100)),
                ('date_facturation', models.DateField()),
                ('Taxe', models.FloatField()),
                ('quantity', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.produit')),
            ],
        ),
    ]
